"use client";

import { useFormContext } from "react-hook-form";
import {
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent } from "@/components/ui/card";
import { AppIcon } from "@/components/shared/app-icon";
import { formatNaira, type ProductFormValues } from "../../schemas/product-form";

const LABEL = "text-xs text-muted-foreground font-medium";

/**
 * Pricing & inventory for the product. The variant concept is no longer
 * exposed: there is a single record (index 0), the SKU is generated by the
 * backend, and there is no add/remove UI.
 */
interface VariantsSectionProps {
  /**
   * True when editing a product that has no variant yet (e.g. bulk-imported
   * without one). Shows a notice; saving the form will create the default.
   */
  missingDefaultVariant?: boolean;
}

export function VariantsSection({
  missingDefaultVariant = false,
}: VariantsSectionProps) {
  const { control } = useFormContext<ProductFormValues>();

  return (
    <div className="space-y-4 pt-6 border-t border-border">
      <div className="flex items-center gap-2">
        <div className="size-7 bg-primary/10 rounded-full flex items-center justify-center">
          <AppIcon icon="solar:tag-price-linear" className="size-4 text-primary-ink" />
        </div>
        <div>
          <h3 className="text-sm font-semibold tracking-tight text-foreground">
            Pricing & Inventory
          </h3>
          <p className="text-xs text-muted-foreground">
            Set this product&apos;s price, cost, and stock
          </p>
        </div>
      </div>

      {missingDefaultVariant && (
        <div className="flex items-start gap-2 rounded-lg border border-warning/30 bg-warning/10 p-3 text-warning-ink">
          <AppIcon
            icon="solar:danger-triangle-linear"
            className="size-4 mt-0.5 shrink-0"
          />
          <p className="text-xs">
            This product&apos;s variant is currently inactive, so its pricing
            isn&apos;t loaded here. Reactivate the existing variant (run the
            variant backfill) — editing the fields below is disabled to avoid
            creating a duplicate variant.
          </p>
        </div>
      )}

      <Card className="bg-muted/10 overflow-hidden p-0">
        <CardContent className="p-4">
          <fieldset
            disabled={missingDefaultVariant}
            className="space-y-4 border-0 p-0 disabled:opacity-60"
          >
          <FormField
            control={control}
            name="variants.0.sku"
            render={({ field }) => (
              <FormItem>
                <FormLabel className={LABEL}>Part Number (SKU)*</FormLabel>
                <FormControl>
                  <Input
                    {...field}
                    className="h-8 text-xs"
                    placeholder="e.g. PC14250"
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <FormField
              control={control}
              name="variants.0.condition"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className={LABEL}>Condition</FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger className="h-8 text-xs w-full">
                        <SelectValue />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="NEW">New</SelectItem>
                      <SelectItem value="REFURBISHED">Refurbished</SelectItem>
                      <SelectItem value="USED">Used</SelectItem>
                      <SelectItem value="OPEN_BOX">Open Box</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="variants.0.sourcingType"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className={LABEL}>Sourcing</FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger className="h-8 text-xs w-full">
                        <SelectValue />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="INHOUSE">In-House</SelectItem>
                      <SelectItem value="OUTSOURCED">Outsourced</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <FormField
              control={control}
              name="variants.0.price"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className={LABEL}>Price (₦)*</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      className="h-8 text-xs font-medium"
                      onChange={(e) => field.onChange(formatNaira(e.target.value))}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="variants.0.costPrice"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className={LABEL}>Cost (₦)</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      className="h-8 text-xs"
                      onChange={(e) => field.onChange(formatNaira(e.target.value))}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="variants.0.stockQuantity"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className={LABEL}>Stock</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      {...field}
                      onChange={(e) => field.onChange(e.target.valueAsNumber || 0)}
                      className="h-8 text-xs"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="variants.0.lowStockThreshold"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className={LABEL}>Threshold</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      {...field}
                      onChange={(e) => field.onChange(e.target.valueAsNumber || 0)}
                      className="h-8 text-xs"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>
          </fieldset>
        </CardContent>
      </Card>
    </div>
  );
}
